### ISSUE TITLE
Relative paths don't work with `TabularDataset.from_path`

### ISSUE THREAD

**Issue by yukw777** [Open-ASAPP/flambe#15]
**Describe the bug**
You can't quite use relative paths with `TabularDataset.from_path` b/c the current working directory is the output directory.
```
os.getcwd()
'/path/to/your/project/flambe-output/output__experiment/dataset/0_2019-08-06_20-56-50cyx6metq'
```
If you use a relative path like `../../../../data`, it'd work, but this is not really intuitive.

**To Reproduce**
1. Create a yaml file similar to the one below:
```yaml
!Experiment

name: experiment
pipeline:
  dataset: !TabularDataset.from_path
    train_path: data/train.csv  # any local path
    val_path: data/val.csv  # any local path
    test_path: data/test.csv  # any local path
```
2. You'll get the following error:
```
(pid=15596) Warning: failed to load file {file_path}
(pid=15596) [Errno 2] File b'data/train.csv' does not exist: b'data/train.csv'
```

**Expected behavior**
The expectation is that the relative path would start from the directory where the yaml file is.

**Screenshots**

**Software Versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version 3.6.8
 - PyTorch Version 1.1
 - Flambé Version 0.4.1

**Additional context**

**Comment by jeremyasapp** [comment]
This is an unfortunate case. We have a mechanism that we use to provide paths inside the config. The motivation was that we wanted to make it easy to modify paths when sharing a configuration with someone else. You can use relative or absolute paths in our resources mechanism:

```
!Experiment

name: experiment
resources:
    train: data/train.csv  # any local path
    val: data/val.csv  # any local path

pipeline:
  dataset: !TabularDataset.from_path
    train_path: @train
    val_path: @val
    
```

Can you let me know if that works?

**Comment by yukw777** [comment]
@jeremyasapp ah sorry about this, I need to read the doc more carefully. 

Following the doc, this worked:
```
!Experiment

name: experiment
resources:
  local:
    train: data/train.csv
    val: data/val.csv
    test: data/test.csv
pipeline:
  dataset: !TabularDataset.from_path
    train_path: !@ train # notice the space between !@ and train
    val_path: !@ val # notice the space between !@ and val
    test_path: !@ test # notice the space between !@ and test
```

Closing.
