### ISSUE TITLE
BERT fine-tuning example in docs seems broked

### ISSUE THREAD

**Issue by williamabrwolf** [Open-ASAPP/flambe#26]
**Describe the bug**

I run the example, and it doesn't work.

**To Reproduce**

Paste the following into a file called `foo.yaml`:

```yaml
!Experiment

name: foo
pipeline:
  dataset: !SSTDataset
    transform:
        text: !BERTTextField.from_alias
            alias: 'bert-base-uncased'
            lower: true
        label: !LabelField

  teacher: !TextClassifier
    embedder: !Embedder
      embedding: !BERTEmbeddings.from_alias
        path: 'bert-base-uncased'
        embedding_freeze: True
      encoder: !BERTEncoder.from_alias
        path: 'bert-base-uncased'
        pool_last: True
    output_layer: !SoftmaxLayer
      input_size: !@ teacher.embedder.encoder.config.hidden_size
      output_size: !@ dataset.label.vocab_size  # We link the to size of the label space

  student: !TextClassifier
    embedder: !Embedder
      embedding: !BERTEmbeddings.from_alias
        path: 'bert-base-uncased'
        embedding_freeze: True
      encoder: !PooledRNNEncoder
        rnn_type: sru
        n_layers: 2
        hidden_size: 256
        pooling: last
    output_layer: !SoftmaxLayer
      input_size: !@ student.embedder.encoder.hidden_size
      output_size: !@ dataset.label.vocab_size

  finetune: !Trainer
    dataset: !@ dataset
    train_sampler: !BaseSampler
      batch_size: 16
    val_sampler: !BaseSampler
      batch_size: 16
    model: !@ teacher
    loss_fn: !torch.NLLLoss
    metric_fn: !Accuracy
    optimizer: !AdamW
      params: !@ finetune.model.trainable_params
      lr: 0.00005

  distill: !DistillationTrainer
    dataset: !@ dataset
    train_sampler: !BaseSampler
      batch_size: 16
    val_sampler: !BaseSampler
      batch_size: 16
    teacher_model: !@ finetune.model
    student_model: !@ student
    loss_fn: !torch.NLLLoss
    metric_fn: !Accuracy
    optimizer: !torch.Adam
      params: !@ distill.student_model.trainable_params
      lr: 0.00005
    alpha_kl: 0.5
    temperature: 1
```

Then, run `flambe foo.yaml`.

NB: I changed the line `input_size: !@ model.embedder.encoder.config.hidden_size` to `input_size: !@ teacher.embedder.encoder.config.hidden_size`.

**Expected behavior**

Experiment works.

**Screenshots**

Error: `AttributeError: 'BERTTextField' object has no attribute 'embeddings'`

**Software Versions (please complete the following information):**
